meta_product_name: "ClassyCars"
meta_title: "ClassyCars - Book your next adventure with us"
meta_description: "A platform that allows users to rent luxury cars for special occasions."
meta_image: "ferrari.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
